version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Rpass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - mysql

  backend:
    build:
      context: ./back_end
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
      - mysql
    volumes:
    - ./back_end:/app

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"  # You can change this port to the one used by your frontend app
