version: '3'

services:
  app-test:
    build:
      context: ./back_end
      dockerfile: dockerfile.test  # Assurez-vous que c'est le bon nom du fichier
    depends_on:
      - elasticsearch
      - mysql
    volumes:
      - ./back_end:/app  # Montez tout le dossier back_end dans le conteneur Docker

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Rpass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - mysql

 
