# Utilisez une image Alpine Linux avec Python
FROM python:3.9-alpine

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez les fichiers nécessaires dans le conteneur
COPY . .

# Installez les dépendances
RUN apk add --no-cache \
    build-base \
    mariadb-dev \
    linux-headers \
    && pip install --no-cache-dir -r requirements.txt

# Exposez le port sur lequel votre application Flask va écouter
EXPOSE 5000

# Commande pour lancer votre application Flask
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
